### ISSUE TITLE
Crash upon start 1.15.2

### ISSUE THREAD

**Issue by LLjo** [fabbe50/Teemos-Minecraft-Utilities#1]
Using forge 31.2.30 I get this message on server start:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/10/20 2:48 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.redirect$zzd000$begin(DedicatedServer.java:746) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.customservermsgs.json:MixinDedServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.customservermsgs.json:MixinDedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 25 more
Caused by: net.minecraftforge.fml.ModLoadingException: Teemos Server Utilities has class loading errors
§7null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 25 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 25 more
Caused by: java.lang.RuntimeException: Failed to load hierarchy member net/dv8tion/jda/api/hooks/ListenerAdapter
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:86) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:129) ~[modlauncher-5.1.0.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
	at com.fabbe50.tsu.ServerUtils.<clinit>(ServerUtils.java:31) ~[?:2.0.0] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 25 more
Caused by: java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.readStream(ClassReader.java:310) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[asm-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:129) ~[modlauncher-5.1.0.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:340) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
	at com.fabbe50.tsu.ServerUtils.<clinit>(ServerUtils.java:31) ~[?:2.0.0] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
	at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3633376136 bytes (3465 MB) / 4294967296 bytes (4096 MB) up to 21474836480 bytes (20480 MB)
	CPUs: 12
	JVM Flags: 20 total; -Xms4G -Xmx20G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.30
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.3.1
		kotlinfml@1.5.2
	Mod List: ~~ERROR~~ NullPointerException: null
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by fabbe50** [comment]
I can't replicate the issue, does it work with an older version of Forge?
